---
- name: Ensure that CNI installation directory exists
  file:
    path: "{{ cni_installation_path }}"
    state: directory
    recurse: yes
    
- name: Download CNI plugins to installation directory
  unarchive:
    src: "{{ cni_package_url }}"
    dest: "{{ cni_installation_path }}"
    remote_src: yes