---
- name: Gather all facts
  hosts: master-ubuntu
  gather_facts: no
  pre_tasks:
    - import_role:
        name: common/gather-facts

- name: Patch kube-admin env pods services
  hosts: master-ubuntu[0]
  environment: "{{ env_vars|default({}) }}"
  gather_facts: no
  tasks:

    - import_role:
        name: ubuntu/kubernetes-master
      tags: init

- name: Install kubernetes on ubuntu nodes 
  hosts: all-ubuntu
  become: yes
  environment: "{{ env_vars|default({}) }}"
  gather_facts: no
  tasks:
    - import_role:
        name: ubuntu/common

- name: Install kubernetes on windows nodes 
  hosts: node-windows
  environment: "{{ env_vars|default({}) }}"
  gather_facts: no
  tasks:
    - import_role:
        name: windows/common
      tags:
        - windows::requirements
    - import_role:
        name: windows/docker
      tags:
        - windows::requirements
    - import_role:
        name: windows/cni
      tags:
        - windows::requirements
    - import_role:
        name: windows/kubernetes-node
      tags:
        - windows::requirements
        - windows::node
    - import_role:
        name: windows/flannel
      when: kube_network_plugin == 'flannel'
