---
- name: Gather all facts
  hosts: master-ubuntu
  gather_facts: no
  pre_tasks:
    - import_role:
        name: common/gather-facts

- name: Install kubernetes on ubuntu nodes 
  hosts: all-ubuntu
  become: yes
  environment: "{{ env_vars|default({}) }}"
  gather_facts: no
  tasks:
    - import_role:
        name: ubuntu/common

- name: Install kubernetes on windows nodes 
  hosts: node-windows
  environment: "{{ env_vars|default({}) }}"
  gather_facts: no
  tasks:
    - import_role:
        name: windows/common
    - import_role:
        name: windows/docker
    - import_role:
        name: windows/cni
    - import_role:
        name: windows/kubernetes-node
    - import_role:
        name: windows/flannel
