---
- name: Gather all facts
  hosts: all
  gather_facts: no
  pre_tasks:
    - import_role:
        name: common/gather-facts

- name: Reset kubeadm on all windows nodes
  hosts: node-windows
  environment: "{{ env_vars|default({}) }}"
  gather_facts: no
  tasks:
    - name: Check if kubelet.conf already exists on windows nodes
      win_stat:
        path: C:/etc/kubernetes/kubelet.conf
      register: kubelet_config_state

    - name: Reset kubeadm
      block:
        - name: Delete nodes in inventory
          shell: kubectl delete node {{ kubernetes_node_hostname }} --force
          delegate_to: "{{ kubernetes_master_ip }}"
          delegate_facts: yes

        - name: Reset kubeadm on windows nodes
          win_shell: kubeadm reset

        - name: Ensure that services are stopped on windows nodes
          win_service:
            name: "{{ item }}"
            state: stopped
            force_dependent_services: yes
          with_items:
            - flanneld
            - kube-proxy
            - kubelet

        - name: Execute cleanup scripts
          win_shell: kube-cleanup.ps1
          ignore_errors: yes
      when: kubelet_config_state.stat.exists
